run:
  skip-dirs:
    - node_modules
linters-settings:
  depguard:
    list-type: blacklist
    packages: [ ]
    packages-with-error-message: { }
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: github.com/seedcx/wallet-evm-monitor
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags: [ ]
    disabled-checks: [ ]
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/seedcx/wallet-evm-monitor
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks:
          - argument
          - case
          - condition
          - return
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # don't require nolint directives to be specific about which linter is being skipped
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - exportloopref
    - gochecknoinits
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
    - funlen
  # don't enable:
  # - asciicheck
  # - depguard
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - scopelint
  # - testpackage
